make cocotb_run TB_FRAMEWORK=COCOTB_TB VCD=1 PARAMETER_NAME=Basic_tests_rs_width_64 VERILATOR_EXTRA_ARGS=" -DXIF_X_RFR_WIDTH_32 -GX_RFR_WIDTH=32"
make cocotb_run TB_FRAMEWORK=COCOTB_TB VCD=1 PARAMETER_NAME=Basic_tests_rs_width_64 VERILATOR_EXTRA_ARGS=" -DXIF_X_RFR_WIDTH_64 -GX_RFR_WIDTH=64"
